export const LOAD_DATA = "LOAD_DATA";
export const SET_INSTRUMENT_TYPE = "SET_INSTRUMENT_TYPE";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const SET_ITEMS_PER_PAGE = "SET_ITEMS_PER_PAGE";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const FAVOURITE_TOGGLE = "FAVOURITE_TOGGLE";

